language: node_js
node_js:
- 9.11.1

branches:
  only:
  - master

env:
  global:
  - secure: DdXfKPbmmBQKqwKT260tk+aeF4j8lR86oKc5imY/LJ+yu8xn7G1Z2F7+Rbo+5Q+hrfCSJZRLdM2mG97l6ApaStkXRsXAA0QwhfO6IRYUnvIapntzYoa1ePQo/BItxRX2QwLZcYmV2GRgAI4bXT5N0QhNQeoiz4cZ+pMtP7seVxiseFck7TWklnXrpm5jH6ksxqie2Sxm31Ex/ww8ob3LmsglnzdmbPhv49B010c68R1A/buZITC4pn5WUSnMspVyBxTp0z9hG96o5NTySzQzfuzN5no1Hte/8oiLuzUfq3rXyiLgBJJ7thUU0IqDcJpDMohadwELPducH31Lj7GcgxzqhApV94kigl/MuF49jS5pQ4ZEpoMXKOqQ7FCbXVen5GibqSc28yCM1sj8SUf9b7w3RF0Zpd7hZTuGkS0WHtlQMyyLLIv9XR2yomR+NhcmW4Hc7tSOWmKXOaH873VH+Nqbejr5vpeT6vZbJwXeAwzNDcdyEsGaWv4iB68z/csV4Nd1QwpldHSUi7qQZZr19Clpg6AZ2tguH5sYYmgqOygJ008r1fEnL9gdevdm5nPZAJVcvXpIcHi5fPi+5oW+gp3ZYT52hOcUMLda97X4Jxap+TqHOcRVWJJDe/k34WhoidrGAedivtWCHv5jIOUO59o+SSWpcLRUEmDIF3JNXKs=
  - secure: gM22749rxOLXUzu55hX/SCWJDU+PVCrc/Z7iHWVUmPUlxOKBQrQALKUPIi1wC5kXzu7owevcpG5M2h9ushlw8cVioFcoygg4n8A/MoTHFbAg6lzj562jab5Ok/OPP/lmUdVln8Hs3tmeQ61i3M7b0bqNCD7DaTB4UbCvuRnEcnMNu1xvfn5q38yH/8FfgOmhVB2LHERyGeOzXta0w47aAvyzisasqsIvPjnBPDDfNCjp9WfKzDWBQMkQEqiMt/ySFGH0d1plCWtmD3qIfbq+frQvqgCU4CkR03L7m/WK1XqLqqk8E+6ALvD6tNmViztTiBXZsGoXauxcXkr3X9n/F3nTR0YF9klN2C+CiwbytGodseFnNE8iLLPD5HQCTsv9aey591uT1hYovb0sPUJDYUClxI86UYaWxk2V7UAeCruobUVrNkkRLrPlPrQU/qw1lvrvuheJarXlDTh7uBVFQvZs0cd5fX/4vPY37YG7loXcL4GYa3Fsm+8Osjxf/h4xJ6Hz+l2Prc1OrkX0FzEpcxRSH/ZX9/ZuahWQ4otCXwj8uori0xTfv0DNl/Q5z8208SWFYqvKqF+SvX92jtg2jcJmxaQrBK/lcKmuMzSoqroM5Ckiw/GH9xF8Dfz6CXerXmQ5H5RB16XRTu80AMCz0gkvhaLIfaTx6ZxLgo/pcds=
  - secure: d20TLTfnfkzs4SHdod8MJVc7VPRuay7PucWWvgd51Ha2/5V5ZNJQHU9qx6SwyAvzqDy8ynWT4oSft5bbyC9jBAuR5RRSQDKFsnirSNwYKZY83dWQPLbYVcACSLTg6x+0AJ6LzsTDS9SoOiFI4P325wTx6qn1mXFF7Wq89T9rDPQJaEDs0qAXDCYWv5NGHNW8Z2vdHXVxj25odSqHW0VLUwm1UubWesmb6SoCyckdKAFkhyfsOT6OPyZLCUa9QmBrJo6Eq6qa/un0waTvdDemQAu7bmpmHqi4cEFLTWEP+/fd3rRJ/3MGw6bd4Cv7bjDObYUuCF3QvyNdOrpQDS7axe5kqrZga3Ew0Wb9WL6xNb6Ao/xd0qwTs2epxMuSvnGjc2FAtjbOCnFj4V3xRbwSuDDGjOWxJvFkD4bsN2OYokuWv/wDnXrEl8B2xrPy+sxvqXlyJPLnWtRVgQEY76YL1YFpEdlIhgChw2sOCixTledUUd74bO4B+WdtSoC3Mgrzwe1TWPQ2duQsitvXW4ooht3LzfKSDO5FgG/ZVVQwQKbsxFdVfuVcT+QUBwJJ4M2osuQNNeJfpd/8T+qrnTVVT7gxI+oiscDGpkivnfn5RknYFbaFllP0VEgnwLC1Di1gSCInWdqxl7DLshaZJlTWrDGWmU0Ev20e5dat01O0Okk=
  - REPO_PATH=/opt/salvare

after_success:
- sudo apt-get update
- sudo apt-get install -qq sshpass
- chmod +x deploy
- ./deploy