#!/bin/bash
echo "Deploying..."

ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
sshpass -p $SSH_PASS rsync -r --rsync-path='sudo rsync' --delete-after --quiet --filter=':- .gitignore' ./src/ ${SSH_USER}@${SSH_HOST}:${REPO_PATH}

echo "Deploying finished."